# Site Configuration
site_name: Grog CMS
site_description: An ultra-light content management system
site_url: https://example.com

# Theme and Layout
theme:
  name: default
  colors:
    primary: '#3498db'
    secondary: '#2ecc71'
    text: '#333333'
    background: '#ffffff'
  font:
    family: 'Roboto, sans-serif'
    url: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap'

# Navigation
nav:
  - Home: index.html
  - About: about.html
  - Contact: contact.html

# Footer
footer:
  copyright: '© 2023 Grog CMS'
  links:
    - text: Privacy Policy
      url: /privacy-policy
    - text: Terms of Service
      url: /terms-of-service

# Social Media
social:
  - platform: GitHub
    url: https://github.com/grogcms
  - platform: Twitter
    url: https://twitter.com/grogcms

# GitHub Configuration
github:
  repo_url: https://github.com/GrogSpace/GrogCMS
  edit_uri: edit/main/pages/

# Contact Form
contact_form:
  email: contact@example.com
  subject: Contact Form Submission

